
server:
  port: 8081
  
  servlet: 
    session: 
      timeout: 1800
      
spring:
  profiles: 
    active: local
    include: profile, oauth, email
    
mybatis: 
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*-mapper.xml
  
springdoc: 
  swagger-ui: 
    path: /swagger-ui.html
    use-root-path: true

    