
spring: 
  profiles: 
    group: 
      local: local, oauth-local, email, awss3, gpt
      prod1: prod1, oauth, email, awss3, gpt
      prod2: prod2, oauth, email, awss3, gpt

---

spring: 
  config: 
    activate: 
      on-profile: local
      
---

spring: 
  config: 
    activate: 
      on-profile: prod1
    
---

spring: 
  config: 
    activate: 
      on-profile: prod2