
server:
  port: 8081
  
  servlet: 
    session: 
      timeout: 1800
      
  error:
    include-exception: true       # 오류 응답에 exception 내용을 포함할지 여부
    include-stacktrace: always    # 오류 응답에 stacktrace 내용을 포함할지 여부
      
spring:
  profiles: 
    active: local
    include: profile, oauth, email, awss3
    
  mvc:
    converters:
      preferred-json-mapper: gson
  
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    
mybatis: 
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*-mapper.xml
  
springdoc: 
  swagger-ui: 
    path: /swagger-ui.html
    use-root-path: true


    