
language: java
jdk: 
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    
before_install:
  - chmod +x mvnw

script: "./mvnw clean package"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - alstkdgks@gmail.com